# Database Connection
# The hostname 'dnddmdb-db' matches your service name in docker-compose
spring.datasource.url=jdbc:postgresql://db:5432/car_rental_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# 'update' will automatically create/update tables based on your Java Entity classes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
# Matches the internal port you mapped in docker-compose
server.port=8080